spring.application.name=ApiGatewaySmartSure

server.port=8080

#Spring Cloud Gateway Configuration
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

eureka.client.service-url.defaultZone=http://service-registry-smart-sure:8761/eureka

# Token Configurations
jwt.secret=767BI36HSIUNYD7352198N1SV12BS62428748NDH7878BXB7B65D326B67SBVV6VS62545265776XBHG
jwt.expiration=86400000
internal.secret=JHGUY72638DEGWRT7D4365N89SOQL89234Y3IUTBR7DT4NQ3479387DNBYFGR366746823BETYX

# CORS Allowed
cors.allowed.origins=http://localhost:3000,http://localhost:4200

# Centralized Swagger Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/authService/v3/api-docs
springdoc.swagger-ui.urls[1].name=Policy Service
springdoc.swagger-ui.urls[1].url=/policyService/v3/api-docs
springdoc.swagger-ui.urls[2].name=Claim Service
springdoc.swagger-ui.urls[2].url=/claimService/v3/api-docs
springdoc.swagger-ui.urls[3].name=Admin Service
springdoc.swagger-ui.urls[3].url=/adminService/v3/api-docs
#springdoc.swagger-ui.urls[4].name=Payment Service
#springdoc.swagger-ui.urls[4].url=/paymentService/v3/api-docs

#Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.default.sliding-window-size=10
resilience4j.circuitbreaker.instances.default.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.default.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.default.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.default.permitted-number-of-calls-in-half-open-state=3

#Auth Service Routing
spring.cloud.gateway.routes[0].id=authService-user
spring.cloud.gateway.routes[0].uri=lb://AUTHSERVICE
spring.cloud.gateway.routes[0].predicates=Path=/user/**

spring.cloud.gateway.routes[1].id=authService-api
spring.cloud.gateway.routes[1].uri=lb://AUTHSERVICE
spring.cloud.gateway.routes[1].predicates=Path=/api/auth/**

spring.cloud.gateway.routes[2].id=authService-actuator
spring.cloud.gateway.routes[2].uri=lb://AUTHSERVICE
spring.cloud.gateway.routes[2].predicates=Path=/authService/**
spring.cloud.gateway.routes[2].filters=StripPrefix=1

#Policy Service Routing
spring.cloud.gateway.routes[3].id=policyService-policy
spring.cloud.gateway.routes[3].uri=lb://POLICYSERVICE
spring.cloud.gateway.routes[3].predicates=Path=/api/policies/**

spring.cloud.gateway.routes[4].id=policyService-types
spring.cloud.gateway.routes[4].uri=lb://POLICYSERVICE
spring.cloud.gateway.routes[4].predicates=Path=/api/policy-types/**


#Claim Service Routing
spring.cloud.gateway.routes[5].id=claimService
spring.cloud.gateway.routes[5].uri=lb://CLAIMSERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/claims/**


#Admin Service Routing
spring.cloud.gateway.routes[6].id=adminService
spring.cloud.gateway.routes[6].uri=lb://ADMINSERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/admin/**


spring.cloud.gateway.routes[7].id=paymentService
spring.cloud.gateway.routes[7].uri=lb://PAYMENTSERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/payments/**

# Documentation Routes
spring.cloud.gateway.routes[8].id=authService-docs
spring.cloud.gateway.routes[8].uri=lb://AUTHSERVICE
spring.cloud.gateway.routes[8].predicates=Path=/authService/v3/api-docs/**
spring.cloud.gateway.routes[8].filters=StripPrefix=1

spring.cloud.gateway.routes[9].id=policyService-docs
spring.cloud.gateway.routes[9].uri=lb://POLICYSERVICE
spring.cloud.gateway.routes[9].predicates=Path=/policyService/v3/api-docs/**
spring.cloud.gateway.routes[9].filters=StripPrefix=1

spring.cloud.gateway.routes[10].id=claimService-docs
spring.cloud.gateway.routes[10].uri=lb://CLAIMSERVICE
spring.cloud.gateway.routes[10].predicates=Path=/claimService/v3/api-docs/**
spring.cloud.gateway.routes[10].filters=StripPrefix=1

spring.cloud.gateway.routes[11].id=adminService-docs
spring.cloud.gateway.routes[11].uri=lb://ADMINSERVICE
spring.cloud.gateway.routes[11].predicates=Path=/adminService/v3/api-docs/**
spring.cloud.gateway.routes[11].filters=StripPrefix=1


#Tracing
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.export.prometheus.enabled=true

#Logging Configuration
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG
logging.level.com.smartSure.apiGateway=INFO
logging.level.reactor.netty=INFO
