spring.application.name=AuthService
server.port=8081
spring.cloud.config.enabled=false

spring.datasource.url=jdbc:mysql://mysql:3306/database
spring.datasource.username=root
spring.datasource.password=Arcana
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=767BI36HSIUNYD7352198N1SV12BS62428748NDH7878BXB7B65D326B67SBVV6VS62545265776XBHG
jwt.expiration=86400000
cors.allowed.origins=http://localhost:3000,http://localhost:4200
internal.secret=JHGUY72638DEGWRT7D4365N89SOQL89234Y3IUTBR7DT4NQ3479387DNBYFGR366746823BETYX
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
admin.email=smartSureInsuranceSpring@gmail.com
admin.password=Hello123@
admin.firstname=Smart
admin.lastname=Sure
eureka.client.service-url.defaultZone=http://service-registry-smart-sure:8761/eureka
eureka.instance.prefer-ip-address=true
logging.level.root=INFO
management.endpoints.web.exposure.include=health,info,metrics
#logging.level.root=INFO 
#logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000ms
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smartSureInsuranceSpring@gmail.com
spring.mail.password=esbipdyopshewdvg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true